on:
 push:
   branches:
   - main
   paths:
   - 'cluster/aws01/**'


env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
