on:
 push:
   branches:
   - main
   paths:
   - 'cluster/aws02/cluster.yaml'


env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_02 }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY_02 }}
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE_02 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          ls -la
