on:
 push:
   branches:
   - main
   paths:
   - 'cluster/aws04/cluster.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          ls -la
