on:
 push:
   branches:
   - main
   paths:
   - 'cluster/aws01/cluster.yaml'


env:
 AWS_ACCESS_KEY_ID: ${{ secrets.acc }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.secc }}
 BUCKET_TF_STATE: ${{ secrets.buc }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          ls -la
